apiVersion: novacron.io/v1
kind: CacheIntegration
metadata:
  name: redis-cluster-cache
  namespace: default
spec:
  redisConfig:
    endpoints:
    - "redis-cluster-0.redis-cluster:6379"
    - "redis-cluster-1.redis-cluster:6379"
    - "redis-cluster-2.redis-cluster:6379"
    credentialsSecret: "redis-credentials"
    ha:
      sentinelEnabled: true
      replicas: 3
      sentinelHosts:
      - "redis-sentinel-0.redis-sentinel:26379"
      - "redis-sentinel-1.redis-sentinel:26379"
      - "redis-sentinel-2.redis-sentinel:26379"
    security:
      tlsEnabled: true
      authEnabled: true
      certSecret: "redis-tls-certs"
  
  strategy:
    type: "write-through"
    consistency: "strong"
    levels:
    - name: "L1"
      size: "256MB"
      ttl: "5m"
      strategy: "LRU"
    - name: "L2"
      size: "1GB"
      ttl: "1h"
      strategy: "LFU"
  
  ttlPolicies:
  - pattern: "vm:*"
    ttl: "30m"
    refreshStrategy: "lazy"
  - pattern: "metrics:*"
    ttl: "5m"
    refreshStrategy: "eager"
  - pattern: "config:*"
    ttl: "1h"
    refreshStrategy: "lazy"
  - pattern: "session:*"
    ttl: "15m"
    refreshStrategy: "lazy"
  
  warmingConfig:
    enabled: true
    strategies:
    - type: "preload"
      patterns: ["config:*", "vm:active:*"]
      priority: 1
    - type: "pattern"
      patterns: ["metrics:recent:*"]
      priority: 2
    schedule: "0 */6 * * *"  # Every 6 hours
  
  evictionPolicy:
    algorithm: "LRU"
    memoryThresholds:
      warning: 0.80
      critical: 0.90
      eviction: 0.95