# This is a template file - DO NOT commit actual secrets to version control
# Use tools like Helm, Kustomize, or external secret management systems

apiVersion: v1
kind: Secret
metadata:
  name: orchestration-secrets
  namespace: novacron-orchestration
  labels:
    app.kubernetes.io/name: novacron-orchestration
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  database_url: "postgresql://orchestrator:CHANGE_ME@postgres:5432/novacron_orchestration?sslmode=require"
  redis_url: "redis://redis:6379/1"
  nats_url: "nats://nats:4222"
  jwt_secret: "CHANGE_ME_TO_SECURE_JWT_SECRET_KEY"
  encryption_key: "CHANGE_ME_TO_32_BYTE_ENCRYPTION_KEY"
  
---
apiVersion: v1
kind: Secret
metadata:
  name: orchestration-tls
  namespace: novacron-orchestration
  labels:
    app.kubernetes.io/name: novacron-orchestration
    app.kubernetes.io/component: tls
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    # TLS certificate content goes here
    # This should be generated by cert-manager or provided by your CA
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    # TLS private key content goes here
    # This should be generated by cert-manager or provided by your CA
    -----END PRIVATE KEY-----

---
# Example external secrets configuration (using External Secrets Operator)
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-secretstore
  namespace: novacron-orchestration
spec:
  provider:
    vault:
      server: "https://vault.novacron.local"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "orchestration-role"
          serviceAccountRef:
            name: orchestration-service

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: orchestration-external-secrets
  namespace: novacron-orchestration
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-secretstore
    kind: SecretStore
  target:
    name: orchestration-secrets
    creationPolicy: Owner
  data:
  - secretKey: database_url
    remoteRef:
      key: novacron/orchestration
      property: database_url
  - secretKey: redis_url
    remoteRef:
      key: novacron/orchestration
      property: redis_url
  - secretKey: nats_url
    remoteRef:
      key: novacron/orchestration
      property: nats_url
  - secretKey: jwt_secret
    remoteRef:
      key: novacron/orchestration
      property: jwt_secret
  - secretKey: encryption_key
    remoteRef:
      key: novacron/orchestration
      property: encryption_key