# NovaCron Docker Compose - Ubuntu 24.04 with Python 3.12 support
version: '3.8'

services:
  # Postgres database
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: novacron
    ports:
      - "11432:5432"  # External port >11111 as required
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - novacron-network

  # Hypervisor service
  hypervisor:
    build:
      context: .
      dockerfile: docker/hypervisor.Dockerfile
    image: novacron/hypervisor:latest
    restart: unless-stopped
    privileged: true
    environment:
      NODE_ID: node1
      LOG_LEVEL: info
      STORAGE_PATH: /var/lib/novacron/vms
      CLUSTER_ADDR: api:8090
    volumes:
      - hypervisor_data:/var/lib/novacron/vms
      - /var/run/libvirt:/var/run/libvirt
      - /dev/kvm:/dev/kvm
    depends_on:
      - api
    networks:
      - novacron-network
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G

  # Redis Master for caching and AI Engine
  redis-master:
    image: redis:7-alpine
    restart: unless-stopped
    command: >
      redis-server
      --port 6379
      --bind 0.0.0.0
      --protected-mode no
      --maxmemory 1gb
      --maxmemory-policy allkeys-lru
      --save 900 1
      --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - novacron-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '2.0'

  # AI Engine service (Python 3.12)
  ai-engine:
    build:
      context: .
      dockerfile: ai-engine/Dockerfile
    image: novacron/ai-engine:latest
    restart: unless-stopped
    environment:
      LOG_LEVEL: info
      PYTHON_VERSION: 3.12
      REDIS_URL: redis://redis-master:6379
      MODEL_PATH: /var/lib/novacron/ai-models
    ports:
      - "8093:8093"
    volumes:
      - ai_models:/var/lib/novacron/ai-models
    depends_on:
      redis-master:
        condition: service_healthy
    networks:
      - novacron-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8093/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'

  # API service
  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    image: novacron/api:latest
    restart: unless-stopped
    environment:
      LOG_LEVEL: info
      API_PORT: 8090
      DB_URL: postgresql://postgres:postgres@postgres:5432/novacron
      AUTH_SECRET: ${AUTH_SECRET:-changeme_in_production}
      HYPERVISOR_ADDRS: hypervisor:9000
      # Cache configuration
      REDIS_ADDR: redis-master:6379
      CACHE_ENABLED: true
      CACHE_L1_ENABLED: true
      CACHE_L2_ENABLED: true
      CACHE_L3_ENABLED: false
      CACHE_DEFAULT_TTL: 15m
      CACHE_VM_STATE_TTL: 30s
      CACHE_VM_METRICS_TTL: 15s
    ports:
      - "8090:8090"  # REST API
      - "8091:8091"  # WebSocket API
    depends_on:
      postgres:
        condition: service_healthy
      redis-master:
        condition: service_healthy
    networks:
      - novacron-network

  # Frontend service
  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    image: novacron/frontend:latest
    restart: unless-stopped
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: http://localhost:8090
      NEXT_PUBLIC_WS_URL: ws://localhost:8091
    ports:
      - "8092:3000"
    depends_on:
      - api
    networks:
      - novacron-network

  # Prometheus for metrics
  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    volumes:
      - ./configs/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    networks:
      - novacron-network

  # Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD:-admin}
      GF_USERS_ALLOW_SIGN_UP: 'false'
      GF_INSTALL_PLUGINS: grafana-piechart-panel
    volumes:
      - ./configs/grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
    networks:
      - novacron-network

networks:
  novacron-network:
    driver: bridge

volumes:
  postgres_data:
  hypervisor_data:
  prometheus_data:
  grafana_data:
  redis_data:
  ai_models:  # AI engine models storage
