version: '3.7'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant-code-memory
    ports:
      - "6333:6333"  # GRPC port
      - "6334:6334"  # REST API port
    volumes:
      - ./qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6333
      - QDRANT__SERVICE__HTTP_PORT=6334
    restart: unless-stopped
