# NovaCron Unified Alerting Configuration
# This configuration defines alerting rules and notification channels for 99.9% uptime SLA

global:
  # Global configuration
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@novacron.local'
  smtp_auth_username: 'alerts@novacron.local'
  smtp_auth_password: 'changeme'
  
  # Webhook settings
  webhook_url: 'http://localhost:9093/api/v1/alerts'
  
  # Resolve timeout
  resolve_timeout: 5m

# Templates for alert messages
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# Route tree
route:
  # Root route
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h
  receiver: 'web.hook'
  
  # Specific routes for different alert types
  routes:
    # Critical system alerts
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 0s
      group_interval: 5m
      repeat_interval: 30m
      continue: true
      
    # Performance SLA alerts
    - match_re:
        alertname: '(ResponseTimeSLA|UptimeSLA|ErrorRateSLA).*'
      receiver: 'sla-alerts'
      group_wait: 30s
      group_interval: 2m
      repeat_interval: 1h
      
    # VM management alerts
    - match:
        service: vm-service
      receiver: 'vm-alerts'
      group_interval: 5m
      repeat_interval: 2h
      
    # ML/Orchestration alerts
    - match:
        service: orchestration-service
      receiver: 'orchestration-alerts'
      repeat_interval: 4h
      
    # Federation alerts
    - match:
        service: federation-service
      receiver: 'federation-alerts'
      repeat_interval: 6h
      
    # Backup alerts
    - match:
        service: backup-service
      receiver: 'backup-alerts'
      repeat_interval: 8h

# Inhibition rules to reduce alert noise
inhibit_rules:
  # Inhibit non-critical alerts when critical ones are firing
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']
    
  # Inhibit component alerts when service is down
  - source_match:
      alertname: 'ServiceDown'
    target_match_re:
      alertname: '.*'
    equal: ['service', 'instance']

# Receivers (notification channels)
receivers:
  # Default webhook receiver
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://localhost:9093/api/v1/alerts'
        send_resolved: true
        
  # Critical alerts - immediate notification
  - name: 'critical-alerts'
    email_configs:
      - to: 'oncall@novacron.local'
        from: 'alerts@novacron.local'
        subject: '[CRITICAL] NovaCron Alert: {{ .GroupLabels.alertname }}'
        html: |
          <h2>🚨 Critical Alert</h2>
          <p><strong>Alert:</strong> {{ .GroupLabels.alertname }}</p>
          <p><strong>Severity:</strong> {{ .CommonLabels.severity }}</p>
          <p><strong>Instance:</strong> {{ .CommonLabels.instance }}</p>
          <p><strong>Time:</strong> {{ .CommonAnnotations.timestamp }}</p>
          <p><strong>Description:</strong> {{ .CommonAnnotations.description }}</p>
          {{- if .CommonAnnotations.runbook_url }}
          <p><strong>Runbook:</strong> <a href="{{ .CommonAnnotations.runbook_url }}">{{ .CommonAnnotations.runbook_url }}</a></p>
          {{- end }}
    
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#alerts-critical'
        title: '🚨 Critical NovaCron Alert'
        text: |
          *Alert:* {{ .GroupLabels.alertname }}
          *Severity:* {{ .CommonLabels.severity }}
          *Instance:* {{ .CommonLabels.instance }}
          *Description:* {{ .CommonAnnotations.description }}
        
    webhook_configs:
      - url: 'http://localhost:8080/api/v1/alerts/critical'
        send_resolved: true

  # SLA violation alerts
  - name: 'sla-alerts'
    email_configs:
      - to: 'sla-team@novacron.local'
        subject: '[SLA VIOLATION] NovaCron: {{ .GroupLabels.alertname }}'
        html: |
          <h2>⚠️ SLA Violation</h2>
          <p><strong>Alert:</strong> {{ .GroupLabels.alertname }}</p>
          <p><strong>Service:</strong> {{ .CommonLabels.service }}</p>
          <p><strong>Current Value:</strong> {{ .CommonAnnotations.current_value }}</p>
          <p><strong>Threshold:</strong> {{ .CommonAnnotations.threshold }}</p>
          <p><strong>Impact:</strong> {{ .CommonAnnotations.impact }}</p>
          
    webhook_configs:
      - url: 'http://localhost:8080/api/v1/alerts/sla'
        send_resolved: true
        http_config:
          headers:
            Content-Type: application/json
          
  # VM service alerts
  - name: 'vm-alerts'
    email_configs:
      - to: 'vm-team@novacron.local'
        subject: '[VM ALERT] {{ .GroupLabels.alertname }}'
        
    webhook_configs:
      - url: 'http://localhost:8080/api/v1/alerts/vm'
        send_resolved: true

  # Orchestration alerts
  - name: 'orchestration-alerts'
    email_configs:
      - to: 'orchestration-team@novacron.local'
        subject: '[ORCHESTRATION] {{ .GroupLabels.alertname }}'
        
    webhook_configs:
      - url: 'http://localhost:8080/api/v1/alerts/orchestration'
        send_resolved: true

  # Federation alerts
  - name: 'federation-alerts'
    email_configs:
      - to: 'federation-team@novacron.local'
        subject: '[FEDERATION] {{ .GroupLabels.alertname }}'
        
    webhook_configs:
      - url: 'http://localhost:8080/api/v1/alerts/federation'
        send_resolved: true

  # Backup alerts
  - name: 'backup-alerts'
    email_configs:
      - to: 'backup-team@novacron.local'
        subject: '[BACKUP] {{ .GroupLabels.alertname }}'
        
    webhook_configs:
      - url: 'http://localhost:8080/api/v1/alerts/backup'
        send_resolved: true