apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: novacron-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - novacron.example.com
    secretName: novacron-tls
  rules:
  - host: novacron.example.com
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: novacron-api
            port:
              number: 8080
      - path: /ws
        pathType: Prefix
        backend:
          service:
            name: novacron-api
            port:
              number: 8081
      - path: /
        pathType: Prefix
        backend:
          service:
            name: novacron-frontend
            port:
              number: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: novacron-grafana-ingress
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: novacron-basic-auth
spec:
  tls:
  - hosts:
    - grafana.novacron.example.com
    secretName: grafana-tls
  rules:
  - host: grafana.novacron.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: grafana
            port:
              number: 3000