apiVersion: apps/v1
kind: Deployment
metadata:
  name: novacron-mysql
  namespace: novacron
spec:
  selector:
    matchLabels:
      app: novacron-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: novacron-mysql
    spec:
      containers:
      - image: mysql:8.0
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: root-password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: novacron-secrets
              key: db-name
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: novacron-secrets
              key: db-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: novacron-secrets
              key: db-password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: novacron-mysql
  namespace: novacron
spec:
  ports:
  - port: 3306
  selector:
    app: novacron-mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: novacron
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi