apiVersion: v1
kind: Namespace
metadata:
  name: novacron-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: novacron-operator
  namespace: novacron-system
  labels:
    app: novacron-operator
    version: v2.0.0-enhanced
spec:
  replicas: 1
  selector:
    matchLabels:
      app: novacron-operator
  template:
    metadata:
      labels:
        app: novacron-operator
        version: v2.0.0-enhanced
    spec:
      serviceAccountName: novacron-operator
      containers:
      - name: manager
        image: novacron/k8s-operator:v2.0.0-enhanced
        imagePullPolicy: IfNotPresent
        args:
        - --leader-elect
        - --metrics-bind-address=0.0.0.0:8080
        - --health-probe-bind-address=0.0.0.0:8081
        - --concurrent-reconciles=3
        env:
        - name: NOVACRON_API_URL
          value: "http://novacron-api:8090"
        - name: NOVACRON_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: novacron-api-token
              key: token
              optional: true
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        - containerPort: 8081
          name: health
          protocol: TCP
        - containerPort: 9443
          name: webhook
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: health
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: health
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 65532
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        volumeMounts:
        - name: webhook-certs
          mountPath: /tmp/k8s-webhook-server/serving-certs
          readOnly: true
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: webhook-certs
        secret:
          secretName: novacron-operator-webhook-certs
          optional: true
      - name: tmp
        emptyDir: {}
      terminationGracePeriodSeconds: 10
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
      - key: "kubernetes.io/arch"
        operator: "Equal"
        value: "amd64"
        effect: "NoSchedule"
      - key: "kubernetes.io/arch"
        operator: "Equal"
        value: "arm64"
        effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  name: novacron-operator-metrics
  namespace: novacron-system
  labels:
    app: novacron-operator
    component: metrics
spec:
  ports:
  - name: metrics
    port: 8080
    targetPort: metrics
    protocol: TCP
  selector:
    app: novacron-operator
---
apiVersion: v1
kind: Service
metadata:
  name: novacron-operator-webhook
  namespace: novacron-system
  labels:
    app: novacron-operator
    component: webhook
spec:
  ports:
  - name: webhook
    port: 443
    targetPort: webhook
    protocol: TCP
  selector:
    app: novacron-operator