# NovaCron Production Application Configuration
# Version: 1.0.0
# Description: Comprehensive production application settings

# Server Configuration
server:
  api:
    host: "0.0.0.0"
    port: "${API_PORT:-8091}"
    read_timeout: "30s"
    write_timeout: "30s"
    idle_timeout: "60s"
    shutdown_timeout: "30s"
    max_header_bytes: 1048576 # 1MB
    
  websocket:
    host: "0.0.0.0"
    port: "${WS_PORT:-8093}"
    read_buffer_size: 1024
    write_buffer_size: 1024
    ping_period: "54s"
    pong_wait: "60s"
    write_wait: "10s"
    max_message_size: 512
    
  metrics:
    host: "0.0.0.0"
    port: "${METRICS_PORT:-9090}"
    path: "/metrics"
    enabled: true

# Application Settings
application:
  name: "NovaCron"
  version: "1.0.0"
  environment: "production"
  debug: false
  
  # Feature Flags
  features:
    vm_management: true
    live_migration: true
    snapshots: true
    backups: true
    monitoring: true
    auto_scaling: false # Disabled by default in production
    experimental_features: false

# Logging Configuration
logging:
  level: "INFO"
  format: "json"
  output: "stdout"
  structured: true
  
  # Log Rotation
  file:
    enabled: false # Use stdout in containerized environments
    path: "/var/log/novacron/app.log"
    max_size: "100MB"
    max_age: "30d"
    max_backups: 10
    compress: true
    
  # Audit Logging
  audit:
    enabled: true
    level: "INFO"
    include_request_body: false
    include_response_body: false
    sensitive_fields_mask: "***"
    
  # Request Logging
  access:
    enabled: true
    format: "combined"
    exclude_paths:
      - "/health"
      - "/metrics"
      - "/favicon.ico"

# VM Management Configuration
vm_management:
  # Default VM Settings
  defaults:
    cpu_cores: 2
    memory_mb: 2048
    disk_size_gb: 20
    network_type: "bridge"
    
  # Resource Limits
  limits:
    max_cpu_cores: 32
    max_memory_gb: 128
    max_disk_size_gb: 2048
    max_vms_per_user: 10
    max_vms_per_tenant: 100
    
  # VM Lifecycle
  lifecycle:
    startup_timeout: "5m"
    shutdown_timeout: "2m"
    force_shutdown_timeout: "30s"
    
  # Storage Configuration
  storage:
    base_path: "/var/lib/novacron/vms"
    template_path: "/var/lib/novacron/templates"
    backup_path: "/var/lib/novacron/backups"
    snapshot_path: "/var/lib/novacron/snapshots"
    
    # Storage Policies
    policies:
      thin_provisioning: true
      compression: true
      deduplication: false
      encryption_at_rest: true

# Networking Configuration
networking:
  # Default Network Settings
  default_network: "novacron-bridge"
  
  # Network Policies
  policies:
    isolate_tenants: true
    allow_internet_access: true
    enable_firewall: true
    
  # DHCP Settings
  dhcp:
    enabled: true
    pool_start: "192.168.100.10"
    pool_end: "192.168.100.200"
    lease_time: "24h"
    
  # DNS Settings
  dns:
    enabled: true
    domain: "novacron.local"
    upstream_servers:
      - "1.1.1.1"
      - "8.8.8.8"

# Monitoring and Alerting
monitoring:
  # Metrics Collection
  metrics:
    collection_interval: "30s"
    retention_period: "30d"
    
    # Exporters
    prometheus:
      enabled: true
      namespace: "novacron"
      
    # System Metrics
    system:
      cpu: true
      memory: true
      disk: true
      network: true
      
    # Application Metrics
    application:
      http_requests: true
      websocket_connections: true
      vm_operations: true
      database_queries: true
      
  # Health Checks
  health:
    startup_timeout: "60s"
    liveness_timeout: "10s"
    readiness_timeout: "5s"
    
    checks:
      database: true
      redis: false
      external_services: false
      
  # Alerting Rules
  alerting:
    enabled: true
    notification_channels:
      - "email"
      - "webhook"
      
    rules:
      high_cpu_usage:
        threshold: 80
        duration: "5m"
        severity: "warning"
        
      high_memory_usage:
        threshold: 85
        duration: "5m"
        severity: "warning"
        
      vm_creation_failure:
        threshold: 5
        duration: "1m"
        severity: "critical"
        
      database_connection_failure:
        threshold: 1
        duration: "30s"
        severity: "critical"

# Security Configuration
security:
  # API Security
  api:
    require_authentication: true
    default_permissions: "read"
    admin_endpoints_require_admin: true
    
  # Session Management
  sessions:
    cookie_name: "novacron-session"
    cookie_secure: true
    cookie_http_only: true
    cookie_same_site: "strict"
    
  # CSRF Protection
  csrf:
    enabled: true
    token_length: 32
    header_name: "X-CSRF-Token"
    
  # Input Validation
  validation:
    max_request_size: "10MB"
    sanitize_input: true
    validate_json_schema: true

# Cache Configuration
cache:
  # Redis Configuration (if enabled)
  redis:
    enabled: false
    host: "${REDIS_HOST}"
    port: "${REDIS_PORT:-6379}"
    password: "${REDIS_PASSWORD}"
    database: 0
    
    # Connection Pool
    pool:
      max_idle: 10
      max_active: 100
      idle_timeout: "240s"
      
  # In-Memory Cache
  memory:
    enabled: true
    max_size: "100MB"
    ttl: "1h"
    cleanup_interval: "10m"

# Background Jobs
jobs:
  # Job Scheduler
  scheduler:
    enabled: true
    max_concurrent_jobs: 10
    
  # VM Operations Jobs
  vm_operations:
    cleanup_failed_vms:
      schedule: "0 2 * * *" # Daily at 2 AM
      timeout: "30m"
      
    backup_vms:
      schedule: "0 1 * * 0" # Weekly on Sunday at 1 AM
      timeout: "6h"
      
    update_metrics:
      schedule: "*/5 * * * *" # Every 5 minutes
      timeout: "2m"
      
  # System Maintenance Jobs
  maintenance:
    cleanup_logs:
      schedule: "0 3 * * 0" # Weekly on Sunday at 3 AM
      retention_days: 30
      
    rotate_certificates:
      schedule: "0 4 1 * *" # Monthly on 1st at 4 AM
      advance_notice_days: 7

# Integration Configuration
integrations:
  # External Hypervisors
  hypervisors:
    kvm:
      enabled: true
      connection_uri: "qemu:///system"
      timeout: "30s"
      
    vmware:
      enabled: false
      vcenter_host: "${VCENTER_HOST}"
      username: "${VCENTER_USER}"
      password: "${VCENTER_PASSWORD}"
      
  # Cloud Providers
  cloud:
    aws:
      enabled: false
      region: "${AWS_REGION}"
      access_key_id: "${AWS_ACCESS_KEY_ID}"
      secret_access_key: "${AWS_SECRET_ACCESS_KEY}"
      
    azure:
      enabled: false
      subscription_id: "${AZURE_SUBSCRIPTION_ID}"
      tenant_id: "${AZURE_TENANT_ID}"
      client_id: "${AZURE_CLIENT_ID}"
      client_secret: "${AZURE_CLIENT_SECRET}"
      
  # Notification Services
  notifications:
    email:
      enabled: false
      smtp_host: "${SMTP_HOST}"
      smtp_port: "${SMTP_PORT:-587}"
      smtp_user: "${SMTP_USER}"
      smtp_password: "${SMTP_PASSWORD}"
      from_address: "noreply@novacron.local"
      
    slack:
      enabled: false
      webhook_url: "${SLACK_WEBHOOK_URL}"
      channel: "#novacron-alerts"

# Performance Tuning
performance:
  # HTTP Server Tuning
  http:
    max_idle_conns: 100
    max_idle_conns_per_host: 2
    idle_conn_timeout: "90s"
    tls_handshake_timeout: "10s"
    expect_continue_timeout: "1s"
    
  # Database Connection Tuning
  database:
    max_open_conns: 25
    max_idle_conns: 10
    conn_max_lifetime: "1h"
    conn_max_idle_time: "10m"
    
  # Memory Management
  memory:
    gc_target_percentage: 100
    max_heap_size: "2GB"
    
  # CPU Optimization
  cpu:
    max_procs: 0 # Use all available CPUs
    gomaxprocs_auto: true

# Development and Testing Overrides
development:
  enabled: false
  
  # Development-specific settings (disabled in production)
  dev_features:
    mock_hypervisor: false
    debug_endpoints: false
    cors_allow_all: false
    disable_auth: false
    hot_reload: false

# Compliance and Governance
compliance:
  # Data Governance
  data_governance:
    data_classification: true
    retention_policies: true
    audit_trail: true
    
  # Regulatory Compliance
  regulations:
    gdpr: true
    hipaa: false
    sox: false
    
  # Policy Enforcement
  policies:
    password_complexity: true
    session_timeout: true
    access_logging: true
    data_encryption: true

# Disaster Recovery
disaster_recovery:
  # Backup Strategy
  backup:
    frequency: "daily"
    retention: "30d"
    offsite_backup: true
    encryption: true
    
  # Recovery Procedures
  recovery:
    rpo: "1h" # Recovery Point Objective
    rto: "4h" # Recovery Time Objective
    automated_failover: false
    
# Resource Quotas (Multi-tenancy)
quotas:
  default_tenant:
    max_vms: 50
    max_cpu_cores: 100
    max_memory_gb: 200
    max_storage_gb: 1000
    
  resource_monitoring:
    enabled: true
    alert_threshold: 80 # percentage
    enforcement: "soft" # soft, hard