# NovaCron Production Security Configuration
# Version: 1.0.0
# Description: Comprehensive security settings for production deployment

# TLS/SSL Configuration
tls:
  enabled: true
  cert_file: "/etc/novacron/certs/server.crt"
  key_file: "/etc/novacron/certs/server.key"
  ca_file: "/etc/novacron/certs/ca.crt"
  min_version: "1.2"
  max_version: "1.3"
  cipher_suites:
    - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
    - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
    - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
    - "TLS_RSA_WITH_AES_256_GCM_SHA384"
    - "TLS_RSA_WITH_AES_128_GCM_SHA256"
  client_auth: false # Set to true for mutual TLS
  
# Authentication & Authorization
auth:
  jwt:
    secret: "${JWT_SECRET}" # Must be set via environment variable
    algorithm: "HS256"
    expiration: "8h"
    issuer: "novacron"
    audience: "novacron-api"
    
  session:
    timeout: "8h"
    cleanup_interval: "1h"
    secure_cookies: true
    same_site: "strict"
    
  password_policy:
    min_length: 12
    require_uppercase: true
    require_lowercase: true
    require_numbers: true
    require_special_chars: true
    max_age_days: 90
    history_count: 12
    
  mfa:
    enabled: true
    issuer: "NovaCron"
    algorithm: "SHA1"
    digits: 6
    period: 30
    
  lockout:
    max_attempts: 5
    lockout_duration: "15m"
    reset_after: "1h"

# Rate Limiting
rate_limiting:
  enabled: true
  global:
    requests_per_minute: 1000
    burst: 100
    
  per_ip:
    requests_per_minute: 60
    burst: 10
    
  auth_endpoints:
    requests_per_minute: 10
    burst: 3
    lockout_duration: "5m"
    
  api_endpoints:
    requests_per_minute: 120
    burst: 20

# CORS Configuration
cors:
  enabled: true
  allowed_origins:
    - "https://*.novacron.local"
    - "https://*.${DOMAIN_NAME}"
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "PATCH"
    - "OPTIONS"
  allowed_headers:
    - "Accept"
    - "Authorization"
    - "Content-Type"
    - "X-CSRF-Token"
    - "X-Requested-With"
  exposed_headers:
    - "X-Total-Count"
    - "X-Rate-Limit-Remaining"
  allow_credentials: true
  max_age: 86400

# Security Headers
security_headers:
  enabled: true
  hsts:
    max_age: 31536000 # 1 year
    include_subdomains: true
    preload: true
  content_type_options: "nosniff"
  frame_options: "DENY"
  xss_protection: "1; mode=block"
  referrer_policy: "strict-origin-when-cross-origin"
  content_security_policy: >-
    default-src 'self';
    script-src 'self' 'unsafe-inline' 'unsafe-eval';
    style-src 'self' 'unsafe-inline';
    img-src 'self' data: https:;
    font-src 'self';
    connect-src 'self' wss: ws:;
    frame-ancestors 'none';
  permissions_policy: >-
    camera=(),
    microphone=(),
    geolocation=(),
    payment=(),
    usb=()

# API Security
api_security:
  api_keys:
    enabled: true
    header_name: "X-API-Key"
    key_length: 64
    rotation_interval: "30d"
    
  request_validation:
    max_request_size: "10MB"
    timeout: "30s"
    validate_content_type: true
    
  response_headers:
    server: "NovaCron"
    remove_headers:
      - "X-Powered-By"
      - "Server"
      - "X-AspNetMvc-Version"
      
# Encryption Configuration
encryption:
  at_rest:
    algorithm: "AES-256-GCM"
    key_rotation_interval: "90d"
    
  in_transit:
    require_tls: true
    verify_certificates: true
    
  database:
    encrypt_sensitive_fields: true
    key_derivation_rounds: 100000

# Audit & Compliance
audit:
  enabled: true
  log_level: "INFO"
  retention_days: 365
  sensitive_data_masking: true
  
  events:
    authentication: true
    authorization: true
    data_access: true
    configuration_changes: true
    admin_actions: true
    failed_requests: true
    
  storage:
    type: "database" # or "file", "syslog", "elasticsearch"
    batch_size: 100
    flush_interval: "10s"

# Network Security
network:
  trusted_proxies:
    - "10.0.0.0/8"
    - "172.16.0.0/12"
    - "192.168.0.0/16"
    - "127.0.0.1/8"
    
  ip_allowlist:
    enabled: false
    addresses: []
    
  ip_blocklist:
    enabled: true
    addresses:
      - "0.0.0.0/32" # Placeholder - add known bad IPs
      
  max_connections: 1000
  connection_timeout: "30s"
  keep_alive_timeout: "60s"

# File Upload Security
file_uploads:
  enabled: true
  max_file_size: "100MB"
  allowed_extensions:
    - ".iso"
    - ".img"
    - ".qcow2"
    - ".vmdk"
    - ".vhd"
  virus_scanning:
    enabled: false # Set to true if antivirus is available
    quarantine_infected: true
    
# Secrets Management
secrets:
  vault:
    enabled: false # Set to true if using HashiCorp Vault
    address: "${VAULT_ADDR}"
    token: "${VAULT_TOKEN}"
    
  environment_variables:
    required:
      - "JWT_SECRET"
      - "DATABASE_PASSWORD"
      - "API_ENCRYPTION_KEY"
      
# Security Monitoring
monitoring:
  intrusion_detection:
    enabled: true
    failed_login_threshold: 10
    unusual_activity_threshold: 50
    
  vulnerability_scanning:
    enabled: false # Set to true if vulnerability scanner is available
    scan_interval: "24h"
    
  security_alerts:
    enabled: true
    webhook_url: "${SECURITY_WEBHOOK_URL}"
    email_recipients:
      - "security@novacron.local"

# Compliance Standards
compliance:
  standards:
    - "ISO27001"
    - "SOC2"
    - "GDPR"
    
  data_classification:
    levels:
      - "public"
      - "internal"
      - "confidential"
      - "restricted"
      
  retention_policies:
    audit_logs: "7y"
    user_data: "5y"
    metrics: "2y"
    backups: "1y"

# Development/Testing Overrides (disabled in production)
development:
  enabled: false
  disable_tls: false
  allow_insecure_connections: false
  debug_endpoints: false
  cors_allow_all_origins: false