# NovaCron Security Hardening Configuration
# Ubuntu 24.04 LTS Enterprise Security Standards

security_hardening:
  version: "2.0"
  compliance_standards:
    - "CIS_Ubuntu_24.04_LTS"
    - "NIST_Cybersecurity_Framework"
    - "ISO_27001"
    - "SOC2_Type_II"
  
  # System-Level Security
  system_security:
    secure_boot:
      enabled: true
      custom_keys: true
      db_keys: "/etc/novacron/security/db.key"
      kek_keys: "/etc/novacron/security/kek.key"
      pk_keys: "/etc/novacron/security/pk.key"
      
    tpm_integration:
      enabled: true
      version: "2.0"
      attestation: true
      key_storage: true
      sealed_secrets: true
      
    kernel_hardening:
      kaslr: true                    # Kernel Address Space Layout Randomization
      smep: true                     # Supervisor Mode Execution Prevention
      smap: true                     # Supervisor Mode Access Prevention
      kpti: true                     # Kernel Page Table Isolation
      ibrs: true                     # Indirect Branch Restricted Speculation
      ibpb: true                     # Indirect Branch Prediction Barrier
      ssbd: true                     # Speculative Store Bypass Disable
      
    filesystem_security:
      encrypted_storage:
        enabled: true
        algorithm: "aes-xts-plain64"
        key_size: 256
        luks_version: 2
        pbkdf: "argon2id"
        
      mount_options:
        /tmp: "nodev,nosuid,noexec"
        /var/tmp: "nodev,nosuid,noexec"
        /dev/shm: "nodev,nosuid,noexec"
        /home: "nodev,nosuid"
        
      file_permissions:
        suid_audit: true
        world_writable_check: true
        unowned_files_check: true

  # AppArmor Configuration  
  apparmor:
    enabled: true
    mode: "enforce"
    profiles:
      novacron_api:
        path: "/etc/apparmor.d/novacron-api"
        mode: "enforce"
        
      novacron_hypervisor:
        path: "/etc/apparmor.d/novacron-hypervisor"
        mode: "enforce"
        
      novacron_llm_engine:
        path: "/etc/apparmor.d/novacron-llm-engine"
        mode: "enforce"
        
      novacron_network_manager:
        path: "/etc/apparmor.d/novacron-network-manager"
        mode: "enforce"
        
    policy_updates:
      automatic: false
      review_required: true
      
  # SELinux Integration (Optional)
  selinux:
    enabled: false  # Can be enabled for additional MAC
    mode: "enforcing"
    policy: "targeted"
    
  # Network Security
  network_security:
    firewall:
      enabled: true
      default_policy: "deny"
      management_interface: "eth0"
      
      zones:
        public:
          interfaces: ["eth0"]
          services: ["ssh", "https"]
          ports:
            - "22/tcp"    # SSH
            - "443/tcp"   # HTTPS
            - "8090/tcp"  # NovaCron API
            
        internal:
          interfaces: ["eth1", "eth2"]
          services: ["novacron-internal"]
          ports:
            - "8091/tcp"  # WebSocket
            - "9000/tcp"  # Hypervisor
            - "5432/tcp"  # PostgreSQL
            - "9090/tcp"  # Prometheus
            
        storage:
          interfaces: ["eth3"]
          services: ["zfs", "nfs"]
          
        dmz:
          interfaces: ["eth4"]
          services: ["monitoring"]
          
    encryption:
      tls:
        min_version: "1.3"
        cipher_suites:
          - "TLS_AES_256_GCM_SHA384"
          - "TLS_CHACHA20_POLY1305_SHA256"
          - "TLS_AES_128_GCM_SHA256"
        certificate_management:
          provider: "lets_encrypt"
          auto_renewal: true
          
      ipsec:
        enabled: true
        protocol: "esp"
        encryption: "aes256"
        authentication: "sha256"
        dh_group: "modp2048"
        
      wireguard:
        enabled: true
        port: 51820
        private_key_path: "/etc/novacron/security/wg-private.key"
        
    intrusion_detection:
      enabled: true
      system: "suricata"
      rules:
        - "emerging-threats"
        - "novacron-custom"
      log_location: "/var/log/suricata/"
      
    ddos_protection:
      enabled: true
      rate_limiting:
        api_requests: "1000/min"
        websocket_connections: "100/min"
        ssh_attempts: "10/min"
        
  # Identity and Access Management
  identity_management:
    authentication:
      multi_factor: true
      password_policy:
        min_length: 14
        complexity: true
        history: 12
        max_age: 90
        
      jwt_tokens:
        algorithm: "RS256"
        expiry: "1h"
        refresh_token: true
        
      oauth2:
        enabled: true
        providers: ["google", "github", "microsoft"]
        
    authorization:
      rbac:
        enabled: true
        roles:
          admin:
            permissions: ["*"]
            
          operator:
            permissions:
              - "vm:read"
              - "vm:create"
              - "vm:update"
              - "vm:migrate"
              
          viewer:
            permissions:
              - "vm:read"
              - "monitoring:read"
              
      policies:
        principle_of_least_privilege: true
        separation_of_duties: true
        
    session_management:
      timeout: 3600  # 1 hour
      concurrent_sessions: 5
      session_fixation_protection: true

  # VM Security
  vm_security:
    isolation:
      hypervisor: "kvm"
      hardware_virtualization: true
      iommu: true
      nested_virtualization: false
      
    memory_protection:
      aslr: true
      dep: true
      guard_pages: true
      
    disk_encryption:
      enabled: true
      per_vm_keys: true
      key_derivation: "pbkdf2"
      
    network_policies:
      default_deny: true
      micro_segmentation: true
      vxlan_isolation: true
      
    integrity_monitoring:
      enabled: true
      file_integrity: true
      configuration_monitoring: true
      runtime_attestation: true
      
  # Secret Management
  secret_management:
    vault_integration:
      enabled: true
      address: "https://vault.novacron.internal:8200"
      auth_method: "kubernetes"
      
    key_rotation:
      automatic: true
      frequency: "monthly"
      
    secrets:
      database_credentials:
        rotation_frequency: "weekly"
        
      api_keys:
        rotation_frequency: "monthly"
        
      tls_certificates:
        rotation_frequency: "quarterly"
        auto_renewal: true

  # Audit and Compliance
  audit:
    logging:
      enabled: true
      location: "/var/log/audit/"
      retention: "1y"
      
    events:
      - user_authentication
      - privilege_escalation
      - file_access
      - network_connections
      - configuration_changes
      - vm_operations
      
    compliance_reporting:
      enabled: true
      frequency: "monthly"
      formats: ["pdf", "json", "csv"]
      
    log_integrity:
      signing: true
      centralized_logging: true
      tamper_detection: true

  # Vulnerability Management
  vulnerability_management:
    scanning:
      enabled: true
      frequency: "daily"
      tools: ["openvas", "nessus", "qualys"]
      
    patch_management:
      automatic_security_updates: true
      maintenance_window: "sunday_02:00"
      reboot_required: "automatic"
      
    dependency_scanning:
      enabled: true
      tools: ["snyk", "dependabot"]
      
  # Incident Response
  incident_response:
    automated_response:
      enabled: true
      quarantine_suspicious_vms: true
      block_malicious_ips: true
      
    alerting:
      channels: ["email", "slack", "pagerduty"]
      escalation_policy: true
      
    forensics:
      memory_dumps: true
      disk_imaging: true
      network_captures: true
      
  # Backup Security
  backup_security:
    encryption:
      enabled: true
      algorithm: "aes-256-gcm"
      
    access_control:
      separate_credentials: true
      multi_person_authorization: true
      
    integrity:
      checksums: true
      signing: true
      
    testing:
      restoration_tests: "monthly"
      integrity_verification: "weekly"

  # Security Monitoring
  security_monitoring:
    siem_integration:
      enabled: true
      system: "splunk"
      
    threat_intelligence:
      feeds: ["misp", "otx", "threatcrowd"]
      
    behavioral_analytics:
      user_behavior: true
      vm_behavior: true
      network_behavior: true
      
    metrics:
      - failed_authentication_attempts
      - privilege_escalation_attempts
      - suspicious_network_activity
      - malware_detections
      - policy_violations

  # Compliance Checks
  compliance_checks:
    cis_benchmarks:
      enabled: true
      auto_remediation: false
      
    nist_framework:
      enabled: true
      maturity_assessment: true
      
    gdpr_compliance:
      data_protection: true
      privacy_by_design: true
      
    hipaa_compliance:
      enabled: false  # Enable for healthcare deployments
      
  # Security Training
  security_training:
    awareness_program: true
    phishing_simulation: true
    incident_response_drills: "quarterly"