import { 
  Loader2, 
  ChevronLeft, 
  ChevronRight, 
  Check, 
  X, 
  AlertCircle, 
  Info, 
  CheckCircle, 
  XCircle,
  Eye,
  EyeOff,
  Shield,
  ShieldCheck,
  Lock,
  Mail,
  User,
  Users,
  Phone,
  Building,
  ArrowLeft,
  ArrowRight,
  CheckCircle2,
  Calendar,
  Clock,
  Sparkles
} from "lucide-react"

export const Icons = {
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  check: Check,
  cross: X,
  warning: AlertCircle,
  info: Info,
  success: CheckCircle,
  error: XCircle,
  eye: Eye,
  eyeOff: EyeOff,
  shield: Shield,
  shieldCheck: ShieldCheck,
  lock: Lock,
  mail: Mail,
  user: User,
  users: Users,
  phone: Phone,
  building: Building,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  checkCircle2: CheckCircle2,
  calendar: Calendar,
  clock: Clock,
  sparkles: Sparkles,
}