apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: cacheintegrations.novacron.io
spec:
  group: novacron.io
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            required:
            - redisConfig
            - strategy
            properties:
              redisConfig:
                type: object
                required:
                - endpoints
                properties:
                  endpoints:
                    type: array
                    minItems: 1
                    items:
                      type: string
                  credentialsSecret:
                    type: string
                  ha:
                    type: object
                    properties:
                      sentinelEnabled:
                        type: boolean
                      replicas:
                        type: integer
                        format: int32
                      sentinelHosts:
                        type: array
                        items:
                          type: string
                  security:
                    type: object
                    properties:
                      tlsEnabled:
                        type: boolean
                      authEnabled:
                        type: boolean
                      certSecret:
                        type: string
              strategy:
                type: object
                required:
                - type
                properties:
                  type:
                    type: string
                    enum: ["write-through", "write-behind", "read-through", "cache-aside"]
                  levels:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        size:
                          type: string
                        ttl:
                          type: string
                        strategy:
                          type: string
                  consistency:
                    type: string
                    enum: ["strong", "eventual", "weak"]
              ttlPolicies:
                type: array
                items:
                  type: object
                  required:
                  - pattern
                  - ttl
                  properties:
                    pattern:
                      type: string
                    ttl:
                      type: string
                    refreshStrategy:
                      type: string
              warmingConfig:
                type: object
                properties:
                  enabled:
                    type: boolean
                  strategies:
                    type: array
                    items:
                      type: object
                      properties:
                        type:
                          type: string
                        patterns:
                          type: array
                          items:
                            type: string
                        priority:
                          type: integer
                          format: int32
                  schedule:
                    type: string
              evictionPolicy:
                type: object
                required:
                - algorithm
                properties:
                  algorithm:
                    type: string
                    enum: ["LRU", "LFU", "FIFO", "Random"]
                  memoryThresholds:
                    type: object
                    properties:
                      warning:
                        type: number
                      critical:
                        type: number
                      eviction:
                        type: number
          status:
            type: object
            properties:
              clusterHealth:
                type: object
                properties:
                  status:
                    type: string
                    enum: ["healthy", "degraded", "failed"]
                  nodes:
                    type: array
                    items:
                      type: object
                      properties:
                        nodeId:
                          type: string
                        status:
                          type: string
                        role:
                          type: string
                        memory:
                          type: string
                        lastSeen:
                          type: string
                          format: date-time
                  replication:
                    type: string
              performanceMetrics:
                type: object
                properties:
                  hitRate:
                    type: number
                  missRate:
                    type: number
                  responseTime:
                    type: string
                  throughput:
                    type: number
              memoryUsage:
                type: object
                properties:
                  totalMemory:
                    type: string
                  usedMemory:
                    type: string
                  usagePercentage:
                    type: number
                  usageByLevel:
                    type: object
                    additionalProperties:
                      type: string
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                      enum: ["True", "False", "Unknown"]
                    lastTransitionTime:
                      type: string
                      format: date-time
                    reason:
                      type: string
                    message:
                      type: string
              observedGeneration:
                type: integer
                format: int64
    additionalPrinterColumns:
    - name: Strategy
      type: string
      jsonPath: .spec.strategy.type
    - name: Hit Rate
      type: string
      jsonPath: .status.performanceMetrics.hitRate
    - name: Health
      type: string
      jsonPath: .status.clusterHealth.status
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
  scope: Namespaced
  names:
    plural: cacheintegrations
    singular: cacheintegration
    kind: CacheIntegration
    shortNames:
    - cache
    - caches