apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: vmclusters.novacron.io
spec:
  group: novacron.io
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              replicas:
                type: integer
                minimum: 0
                default: 1
              template:
                type: object
                description: Template for VMs in the cluster
                properties:
                  name:
                    type: string
                  namespace:
                    type: string
                required:
                - name
              updateStrategy:
                type: object
                properties:
                  type:
                    type: string
                    enum: ["RollingUpdate", "Recreate"]
                    default: "RollingUpdate"
                  rollingUpdate:
                    type: object
                    properties:
                      maxUnavailable:
                        type: integer
                        minimum: 0
                      maxSurge:
                        type: integer
                        minimum: 0
              autoScaling:
                type: object
                properties:
                  enabled:
                    type: boolean
                  minReplicas:
                    type: integer
                    minimum: 1
                  maxReplicas:
                    type: integer
                    minimum: 1
                  targetCPUUtilization:
                    type: integer
                    minimum: 1
                    maximum: 100
                  targetMemoryUtilization:
                    type: integer
                    minimum: 1
                    maximum: 100
            required:
            - template
          status:
            type: object
            properties:
              replicas:
                type: integer
              readyReplicas:
                type: integer
              availableReplicas:
                type: integer
              observedGeneration:
                type: integer
                format: int64
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                      enum: ["True", "False", "Unknown"]
                    lastTransitionTime:
                      type: string
                      format: date-time
                    reason:
                      type: string
                    message:
                      type: string
    additionalPrinterColumns:
    - name: Desired
      type: integer
      jsonPath: .spec.replicas
    - name: Current
      type: integer
      jsonPath: .status.replicas
    - name: Ready
      type: integer
      jsonPath: .status.readyReplicas
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
  scope: Namespaced
  names:
    plural: vmclusters
    singular: vmcluster
    kind: VMCluster
    shortNames:
    - vmc