apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: virtualmachines.novacron.io
spec:
  group: novacron.io
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              name:
                type: string
                description: Name of the virtual machine
              template:
                type: object
                description: Template reference for VM creation
                properties:
                  name:
                    type: string
                  namespace:
                    type: string
              config:
                type: object
                description: Inline VM configuration
                properties:
                  resources:
                    type: object
                    properties:
                      cpu:
                        type: object
                        properties:
                          request:
                            type: string
                          limit:
                            type: string
                      memory:
                        type: object
                        properties:
                          request:
                            type: string
                          limit:
                            type: string
                      disk:
                        type: object
                        properties:
                          request:
                            type: string
                  image:
                    type: string
                  command:
                    type: array
                    items:
                      type: string
                  args:
                    type: array
                    items:
                      type: string
                  env:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        value:
                          type: string
              nodeSelector:
                type: object
                additionalProperties:
                  type: string
              restartPolicy:
                type: string
                enum: ["Always", "OnFailure", "Never"]
                default: "Always"
            required:
            - name
          status:
            type: object
            properties:
              phase:
                type: string
                enum: ["Pending", "Running", "Failed", "Succeeded", "Unknown"]
              state:
                type: string
              nodeId:
                type: string
              vmId:
                type: string
              ipAddress:
                type: string
              resourceUsage:
                type: object
                properties:
                  cpu:
                    type: string
                  memory:
                    type: string
                  disk:
                    type: string
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                      enum: ["True", "False", "Unknown"]
                    lastTransitionTime:
                      type: string
                      format: date-time
                    reason:
                      type: string
                    message:
                      type: string
              observedGeneration:
                type: integer
                format: int64
    additionalPrinterColumns:
    - name: State
      type: string
      jsonPath: .status.state
    - name: Node
      type: string
      jsonPath: .status.nodeId
    - name: IP
      type: string
      jsonPath: .status.ipAddress
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
  scope: Namespaced
  names:
    plural: virtualmachines
    singular: virtualmachine
    kind: VirtualMachine
    shortNames:
    - vm
    - vms